### ISSUE TITLE
Thanks for this library

### ISSUE THREAD

**Issue by tedb** [otiai10/primes#2]
Hi, I just wanted to say thanks for writing this library!  I am using it to solve a coding puzzle for AdventofCode.com (http://adventofcode.com/day/20).  Spoiler alert, the sequence is "sum of factors".

**Comment by otiai10** [comment]
Thank you so so much!
I started to write this for my study with [Project Euler](https://projecteuler.net/).

I'm so glad this library could help any other.

![tiqav](https://img.tiqav.com/3yl.jpg)
