### ISSUE TITLE
Suggestion: memoize the list of primes

### ISSUE THREAD

**Issue by tedb** [otiai10/primes#4]
Hello, I used this library in attempt at Advent of Code puzzle day 20.  However, I found the approach I used to be quite slow, due to my repeated use of primes.Factorize().  Digging into it, it seems the library re-calculates the list of primes every time Factorize is run.  If this library is still being maintained, I think it would be a good improvement to memoize (aka cache) the list of primes.  Perhaps append to the primes list if required to factor a higher number than had been requested before.

**Comment by otiai10** [comment]
Thanks!

You're saying about this, right? 
https://github.com/otiai10/primes/blob/master/factor.go#L18

Yep, I prefer readability than speed so far.
But ('cause I knew someone (you) uses this lib, thank you!) I'm willing to improve speed now.

related: #3

**Comment by otiai10** [comment]
naive imple

before

```
BenchmarkUntil         2     756366134 ns/op
BenchmarkFactorize         2     784614548 ns/op
```

after

```
BenchmarkUntil  100000000           17.6 ns/op
BenchmarkFactorize     10000        123662 ns/op
```

https://github.com/otiai10/primes/commit/40b3480a9ee7c3cf1f82d74baa6e3ed1db5b649c

# problem as is

It is effective ONLY WHEN you repeat calculations on EXACTLY equal numbers.

# solution to be

thinking...

**Comment by otiai10** [comment]
#5
